### ISSUE TITLE
Please re-add module.nix

### ISSUE THREAD

**Issue by thoughtpolice** [edolstra/dwarffs#8]
I would really like to use DwarfFS so that I can turn off global debug packages for my system -- not having symbols at debug time is pretty much the only reason to enable it!

However, 2f984abe63b6d76bb55c22dc48d61f744ef8ce0b inlined the `module.nix` file into the new flake description. I understand the desire to use self-contained tools like `dwarffs` for experimenting with Flakes, but I'm not running the Flake branch, and dwarffs is useful without it!

I'd like to propose re-adding the old `module.nix` file so DwarfFS can be used by non-flake users without writing their own. I do not know if code reuse is possible, but I don't think it's worth it for such a conceptually simple expression.

Alternatively, packaging `dwarffs` upstream inside Nixpkgs would also be great IMO, but I understand if you don't want to do that since it'll directly conflict with the flake experiment...

**Comment by emilazy** [comment]
I'd also like to see this return; alternatively, I'd be happy to use `flake.nix` if it's possible to merge the `nixosModule` in from my (non-flakes-supporting) config, but I'm not sure how to wire it up.

**Comment by emilazy** [comment]
If anyone wants to use `dwarffs` on NixOS without flakes, the following seems to work:

```nix
{ config, pkgs, lib, ... }:

let
  # <dwarffs> / <dwarffs/flake.nix> also an option if you add it to NIX_PATH
  dwarffs =
    { __toString = _: ./path/to/dwarffs; } //
    (import ./path/to/dwarffs/flake.nix).outputs {
      self = dwarffs;
      nixpkgs = pkgs;
    };
in

{
  imports = [
    # ...
    dwarffs.nixosModules.dwarffs
  ];

  # ...
}
```

**Comment by layus** [comment]
Either that, or the Readme should be updated accordingly. At the moment it literally reads 

```
To enable dwarffs, add the following to your configuration.nix:

    imports = [ (builtins.fetchGit https://github.com/edolstra/dwarffs + "/module.nix") ];
```

which obviously does not work.

PS: necrobumping every year :-). How many years will this stand ?
