### ISSUE TITLE
The nixFlakes in current nixpkgs does not support flake.lock version 5

### ISSUE THREAD

**Issue by bqv** [edolstra/dwarffs#9]
Hi, I pull this into my flake, and attempting to update my lock fails with master because nixFlakes in nixos/nixpkgs/master is now around a month old. If there isn't any significant difference, could the flake.lock in this be monkeypatched to version 4? Alternatively (and preferably), could the version in nixpkgs be updated?

**Comment by bqv** [comment]
For posterity, nixpkgs master at time of writing is at https://github.com/NixOS/nixpkgs/commit/e1a880fca93bb20d91fb079a62c8323f1320d493 and the latest nix version was updated at https://github.com/NixOS/nixpkgs/commit/3b72c55fc5aff74cc7bdef1f15c04c29e5671ab1

**Comment by edolstra** [comment]
`nixFlake` has been updated.
